### PR TITLE
Refactor edit mode and make compatible with diva viewer

### LINKED ISSUE #343: Implement edit mode when using diva.js viewer
The edit mode used previously does not work for diva.js and also could stand to be rewritten more generally. Ideally the same functionality should exist with as much functionality as possible in as utilities available to both the diva.js edit mode and single-page edit mode.

### PR DESCRIPTION
**Pull request by JRegimbal**
This takes care of part of #341 and resolves #343.

## Changes

* Refactor most editing features to a new folder called `UnifiedEdit`.
* Create a `DivaEdit` class.
* Have most editor tools take selectors as inputs to set event listeners. Previously these were hard coded.

~***This should not be merged until more testing is performed.***
The pull request exists to check compatibility with develop, ensure tests are running through travis, and get feedback.~

### CODE REVIEW

**Comment by JRegimbal** [comment]
Currently dealing with an issue where at times there are multiple insert handlers being called for a single click resulting in multiple elements being inserted instead of one.

**Comment by JRegimbal** [comment]
Issue arises when the user clicks on a staff line, triggering one action on the svg container and one on the inner 'definition-scale' element. This can be fixed by only applying the listener to the container svg.

**Comment by vigliensoni** [comment]
Have you done all tests to check compatibility for this? Can we merge?

**Comment by JRegimbal** [comment]
@vigliensoni A few commits were just added, but most tests have been done. Should be close to the point of merging soon.

**Comment by JRegimbal** [comment]
Minor UI fixes need to be made first but after that this seems ready to merge.

**Pull request merged**
