### PR TITLE
✨ Add octave displacement for clefs

### LINKED ISSUE #648: Feature request: a button to correct octave displacement
It is always assumed that a C clef denotes C3 and F-clef F3, but this is not always true. This leads to problems e.g. folio 1r lines 5-6, where two consecutive E's are labelled E3 and E2 because of a clef change.  The user should be able to correct such octave displacements when they arise. 
image

### PR DESCRIPTION
**Pull request by jinh0**
Fixes #648 .

https://user-images.githubusercontent.com/40512164/184015868-62a1abaa-064b-47dd-b8dd-622a0237d8f1.mov

Before this PR can be merged, there's one issue:

@annamorphism or @JoyfulGen , what is the minimum / maximum octave a neume can be? Currently, clef displacement has free reign and can lead to neumes having a -1 octave. From my testing, the maximum octave a neume can be is 6.

### CODE REVIEW

**Comment by annamorphism** [comment]
@jinh0 You mean, in what it can do in Neon, or what it might represent musically? Assuming middle C=C3, chant never goes outside the range G1 to E4 (and even that's pretty generous really). So while you can currently give neumes all sorts of octaves, it really only makes sense to have them go from 1-4.

**Comment by jinh0** [comment]
Hey @annamorphism , sorry, to clarify, this new feature in Neon allows you to have pitches displaced down to F-1 all the way up to C6.

If it doesn't make sense musically, should Neon restrict the user from displacing neumes to pitches below octave 1 / above octave 4?

**Comment by annamorphism** [comment]
@jinh0 I mean, a range from -1 to 6 is pretty sensible and won't break anything.  you could make it even smaller if you wanted to, though.

**Review by yinanazhou — CHANGES_REQUESTED** [review]
- [x] the dropdown menu for clef shape change is not functioning
- [ ] the HTML part for two dropdown menus for clef contains several repeated id attributes

**Review by yinanazhou — APPROVED** [review]

**Pull request merged**
